/**
 * CreateUndo DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { UndoDispositionParams } from "@aegira/core/dispositions";

export function createCreateUndoRequest(overrides: Partial<UndoDispositionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
