/**
 * AssurancePack Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/audit.openapi.types.js";
import { schemas } from "../schemas/audit.schemas.js";

/**
 * Entity: AssurancePackEntity
 * Description: Represents the AssurancePack domain model.
 * Source: schemas.AssurancePack
 * Type: Domain Entity (API)
 */
export const AssurancePackEntitySchema = schemas.AssurancePack;
export type AssurancePackEntity = components["schemas"]["AssurancePack"];
