/**
 * PromotionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepository Port
 *
 * DDD: Application port for promotionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListPromotionAuditInput, ListPromotionAuditOutput } from "../dto/promotion.dto";
export interface PromotionRepository {
  listPromotionAudit(input: ListPromotionAuditInput): Promise<ListPromotionAuditOutput>;
}

export type { ListPromotionAuditInput, ListPromotionAuditOutput } from "../dto/promotion.dto";
