/**
 * RejectAmlHandoff handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { rejectAmlHandoff } from "@aegira/api-server/domains/handoffs/handlers";
import type { HandoffsDDDDependencies } from "@aegira/api-server/domains/handoffs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { HANDOFFS_USE_CASES } from "../__factories__/use-cases.js";

describe("RejectAmlHandoff", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: HandoffsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<HandoffsDDDDependencies>(
      HANDOFFS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRejectAmlHandoff, "execute").mockResolvedValue(useCaseResult);

    await rejectAmlHandoff(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRejectAmlHandoff.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
