/**
 * DispositionMixRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DispositionMixRepository Port
 *
 * DDD: Application port for dispositionmixrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDispositionMixInput, GetDispositionMixOutput } from "../dto/disposition-mix.dto";
export interface DispositionMixRepository {
  getDispositionMix(input: GetDispositionMixInput): Promise<GetDispositionMixOutput>;
}

export type { GetDispositionMixInput, GetDispositionMixOutput } from "../dto/disposition-mix.dto";
