/**
 * CreateCallback DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RequestCareCallbackParams } from "@aegira/core/care";

export function createCreateCallbackRequest(overrides: Partial<RequestCareCallbackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
