/**
 * StatusRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StatusRepository Port
 *
 * DDD: Application port for statusrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCareStatusInput, GetCareStatusOutput } from "../dto/status.dto";
export interface StatusRepository {
  getCareStatus(input: GetCareStatusInput): Promise<GetCareStatusOutput>;
}

export type { GetCareStatusInput, GetCareStatusOutput } from "../dto/status.dto";
