/**
 * Callback DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Callback DTOs
 *
 * DDD: Application DTOs for Callback use cases.
 */

import type { RequestCareCallbackParams } from "@aegira/core/care/types";

export type RequestCareCallbackInput = RequestCareCallbackParams;

export type RequestCareCallbackOutput = {};
