/**
 * Status DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Status DTOs
 *
 * DDD: Application DTOs for Status use cases.
 */

import type { GetCareStatusParams } from "@aegira/core/care/types";

export type GetCareStatusInput = GetCareStatusParams;

export type GetCareStatusOutput = {};
