/**
 * ExecuteCreateDisposition - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDisposition Use Case
 *
 * DDD: Application use case for create Disposition.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDispositionInput, CreateDispositionOutput } from "../dto/disposition.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { DispositionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDisposition {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disposition: DispositionRepository
  ) {}

  async execute(input: CreateDispositionInput): Promise<CreateDispositionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dspId();

    // All field names extracted from OpenAPI spec: code, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.code) {
      throw new ValidationError("code is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (dispositions domain)
    const entityId = this.idGenerator.dspId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.disposition.createDisposition({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDispositionOutput;
  }
}
