/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the dispositions domain.
 * Use these factories in tests to create test data.
 */

export { createCreateUndoRequest } from "./undo/dto/create-undo.dto.factory.js";
export { createDisposition } from "./disposition/entity/disposition.entity.factory.js";
