/**
 * Repository interface for Disposition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DispositionEntity
} from "../models/disposition.entity.js";
import type {
  ListDispositionsParams,
  Disposition
} from "../types/index.js";
/**
 * DispositionRepository Interface
 */
export interface DispositionRepository extends CreateReadRepository<DispositionEntity, Disposition, string, ListDispositionsParams> {

}
