/**
 * Handlers for Acknowledge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { AcknowledgeLatencyBreachInput } from "@aegira/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/scoring/latency-breaches/{breachId}/acknowledge
 * Operation: acknowledgeLatencyBreach
 */
export async function acknowledgeLatencyBreach(
  request: FastifyRequest<{ Params: { breachId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcknowledgeLatencyBreachInput = {
    breachId: request.params.breachId,
  };
  const result = await deps.useCases.acknowledges.get.execute(input);
  return reply.code(200).send(result);
}


