/**
 * Handlers for Latency
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { GetScoringLatencyHealthInput, UpdateScoringLatencyBudgetInput } from "@aegira/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/scoring/latency
 * Operation: getScoringLatencyHealth
 */
export async function getScoringLatencyHealth(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetScoringLatencyHealthInput = {};
  const result = await deps.useCases.latencies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/scoring/latency
 * Operation: updateScoringLatencyBudget
 */
export async function updateScoringLatencyBudget(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateScoringLatencyBudgetInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.latencies.update.execute(input);
  return reply.code(200).send(result);
}


