/**
 * ExecuteListInvestigatorLoad - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListInvestigatorLoad Use Case
 *
 * DDD: Application use case for list Investigator.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListInvestigatorLoadInput, ListInvestigatorLoadOutput } from "../dto/investigator.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { InvestigatorRepository } from "../ports";

export class ExecuteListInvestigatorLoad {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly investigator: InvestigatorRepository
  ) {}

  async execute(input: ListInvestigatorLoadInput): Promise<ListInvestigatorLoadOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cseId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.investigator.listInvestigatorLoad({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListInvestigatorLoadOutput;
  }
}
