/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as auditRoutes from "../../domains/audit/routes/index.js";
import * as careRoutes from "../../domains/care/routes/index.js";
import * as casesRoutes from "../../domains/cases/routes/index.js";
import * as dispositionsRoutes from "../../domains/dispositions/routes/index.js";
import * as entitiesRoutes from "../../domains/entities/routes/index.js";
import * as experimentsRoutes from "../../domains/experiments/routes/index.js";
import * as handoffsRoutes from "../../domains/handoffs/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as metricsRoutes from "../../domains/metrics/routes/index.js";
import * as modelsRoutes from "../../domains/models/routes/index.js";
import * as scoringRoutes from "../../domains/scoring/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "audit", mod: auditRoutes },
  { domain: "care", mod: careRoutes },
  { domain: "cases", mod: casesRoutes },
  { domain: "dispositions", mod: dispositionsRoutes },
  { domain: "entities", mod: entitiesRoutes },
  { domain: "experiments", mod: experimentsRoutes },
  { domain: "handoffs", mod: handoffsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: [
      "authRoutes",
      "signupRoutes",
      "sessionRoutes",
      "tokenRoutes",
      "profileRoutes",
    ],
  },
  { domain: "metrics", mod: metricsRoutes },
  { domain: "models", mod: modelsRoutes },
  { domain: "scoring", mod: scoringRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
