/**
 * ExecuteNoteCareCallOutcome - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteNoteCareCallOutcome Use Case
 *
 * DDD: Application use case for get CallOutcome.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { NoteCareCallOutcomeInput, NoteCareCallOutcomeOutput } from "../dto/call-outcome.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { CallOutcomeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteNoteCareCallOutcome {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly callOutcome: CallOutcomeRepository
  ) {}

  async execute(input: NoteCareCallOutcomeInput): Promise<NoteCareCallOutcomeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.carId();

    // All field names extracted from OpenAPI spec: outcome
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).careStatusId) {
      throw new ValidationError("careStatusId is required");
    }
    const carestatusId = (input as any).careStatusId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.callOutcome.noteCareCallOutcome({ careStatusId: carestatusId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${carestatusId}`);
    }

    return entity as NoteCareCallOutcomeOutput;
  }
}
