/**
 * ExecuteGetWeeklyLift - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetWeeklyLift Use Case
 *
 * DDD: Application use case for get Lift.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetWeeklyLiftInput, GetWeeklyLiftOutput } from "../dto/lift.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { LiftRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetWeeklyLift {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lift: LiftRepository
  ) {}

  async execute(input: GetWeeklyLiftInput): Promise<GetWeeklyLiftOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mtrId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.lift.getWeeklyLift({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetWeeklyLiftOutput;
  }
}
