/**
 * Acknowledge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Acknowledge DTOs
 *
 * DDD: Application DTOs for Acknowledge use cases.
 */

import type { AcknowledgeLatencyBreachParams } from "@aegira/core/scoring/types";

export type AcknowledgeLatencyBreachInput = AcknowledgeLatencyBreachParams;

export type AcknowledgeLatencyBreachOutput = {};
