/**
 * Routes for Undo
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { undoDisposition } from "../handlers/undo.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function undoRoutes(fastify: FastifyInstance) {
  // POST /v1/dispositions/{dispositionId}/undo (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/dispositions/:dispositionId/undo",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dispositionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDispositionsDependenciesForRequest();
        await undoDisposition(request, reply, deps);
      });
    }
  );


}
