/**
 * Disposition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disposition DTOs
 *
 * DDD: Application DTOs for Disposition use cases.
 */

import type { CreateDispositionParams, CreateDispositionRequestInput, ListDispositionsParams } from "@aegira/core/dispositions/types";

export type ListDispositionsInput = ListDispositionsParams;

export type CreateDispositionInput = CreateDispositionParams & CreateDispositionRequestInput;

export type ListDispositionsOutput = {};

export type CreateDispositionOutput = {};
