/**
 * Cases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cases Domain Module - Composition root
 *
 * DDD: Composition root for cases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CaseRepositoryAdapter,
  ClaimRepositoryAdapter,
  HeatmapRepositoryAdapter,
  InvestigatorRepositoryAdapter,
  PriorityPolicyRepositoryAdapter,
  ReassignRepositoryAdapter,
} from "@aegira/adapters/cases";
import { getIdGeneratorService } from "@aegira/adapters";
import type { AdapterDynamoDBClient } from "@aegira/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClaimFraudCase,
  ExecuteGetFraudCase,
  ExecuteGetPriorityPolicy,
  ExecuteGetQueueHeatmap,
  ExecuteListFraudCases,
  ExecuteListInvestigatorLoad,
  ExecuteReassignFraudCase,
  ExecuteUpdatePriorityPolicy,
} from "@aegira/services/cases/usecases";
// Ports (interfaces)
import type {
  CaseRepository,
  ClaimRepository,
  HeatmapRepository,
  InvestigatorRepository,
  PriorityPolicyRepository,
  ReassignRepository,
} from "@aegira/services/cases/ports";

export interface CasesDomainModule {
  repos: {
    cases: CaseRepository;
    claims: ClaimRepository;
    heatmaps: HeatmapRepository;
    investigators: InvestigatorRepository;
    priorityPolicies: PriorityPolicyRepository;
    reassigns: ReassignRepository;
  };
  useCases: {
    cases: {
      get: ExecuteGetFraudCase;
      list: ExecuteListFraudCases;
    };
    claims: {
      get: ExecuteClaimFraudCase;
    };
    heatmaps: {
      get: ExecuteGetQueueHeatmap;
    };
    investigators: {
      list: ExecuteListInvestigatorLoad;
    };
    priorityPolicies: {
      get: ExecuteGetPriorityPolicy;
      update: ExecuteUpdatePriorityPolicy;
    };
    reassigns: {
      get: ExecuteReassignFraudCase;
    };
  };
}

export function buildCasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cases?: CaseRepository;
      claims?: ClaimRepository;
      heatmaps?: HeatmapRepository;
      investigators?: InvestigatorRepository;
      priorityPolicies?: PriorityPolicyRepository;
      reassigns?: ReassignRepository;
    } = {};

    obj.cases = new CaseRepositoryAdapter(dynamoClient);
    obj.claims = new ClaimRepositoryAdapter(dynamoClient);
    obj.heatmaps = new HeatmapRepositoryAdapter(dynamoClient);
    obj.investigators = new InvestigatorRepositoryAdapter(dynamoClient);
    obj.priorityPolicies = new PriorityPolicyRepositoryAdapter(dynamoClient);
    obj.reassigns = new ReassignRepositoryAdapter(dynamoClient);
    return {
      cases: obj.cases!,
      claims: obj.claims!,
      heatmaps: obj.heatmaps!,
      investigators: obj.investigators!,
      priorityPolicies: obj.priorityPolicies!,
      reassigns: obj.reassigns!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    cases: {
      get: new ExecuteGetFraudCase(executionContext, idGenerator, repos.cases),
      list: new ExecuteListFraudCases(executionContext, idGenerator, repos.cases),
    },
    claims: {
      get: new ExecuteClaimFraudCase(executionContext, idGenerator, repos.claims),
    },
    heatmaps: {
      get: new ExecuteGetQueueHeatmap(executionContext, idGenerator, repos.heatmaps),
    },
    investigators: {
      list: new ExecuteListInvestigatorLoad(executionContext, idGenerator, repos.investigators),
    },
    priorityPolicies: {
      get: new ExecuteGetPriorityPolicy(executionContext, idGenerator, repos.priorityPolicies),
      update: new ExecuteUpdatePriorityPolicy(executionContext, idGenerator, repos.priorityPolicies),
    },
    reassigns: {
      get: new ExecuteReassignFraudCase(executionContext, idGenerator, repos.reassigns),
    },
  };
  return { repos, useCases: useCases as CasesDomainModule["useCases"] };
}
