/**
 * InvestigatorRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvestigatorRepository Port
 *
 * DDD: Application port for investigatorrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListInvestigatorLoadInput, ListInvestigatorLoadOutput } from "../dto/investigator.dto";
export interface InvestigatorRepository {
  listInvestigatorLoad(input: ListInvestigatorLoadInput): Promise<ListInvestigatorLoadOutput>;
}

export type { ListInvestigatorLoadInput, ListInvestigatorLoadOutput } from "../dto/investigator.dto";
