/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { assurancePackRoutes } from "./assurance-pack.routes.js";
export { caseAccessRoutes } from "./case-access.routes.js";
export { promotionRoutes } from "./promotion.routes.js";
export { retentionRoutes } from "./retention.routes.js";
