/**
 * ExecuteGetScoringLatencyHealth - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetScoringLatencyHealth Use Case
 *
 * DDD: Application use case for get Latency.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetScoringLatencyHealthInput, GetScoringLatencyHealthOutput } from "../dto/latency.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { LatencyRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetScoringLatencyHealth {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly latency: LatencyRepository
  ) {}

  async execute(input: GetScoringLatencyHealthInput): Promise<GetScoringLatencyHealthOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.latency.getScoringLatencyHealth({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetScoringLatencyHealthOutput;
  }
}
