/**
 * ExecuteGetScoreEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetScoreEvent Use Case
 *
 * DDD: Application use case for get Score.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetScoreEventInput, GetScoreEventOutput } from "../dto/score.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { ScoreRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetScoreEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly score: ScoreRepository
  ) {}

  async execute(input: GetScoreEventInput): Promise<GetScoreEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).scoreEventId) {
      throw new ValidationError("scoreEventId is required");
    }
    const scoreeventId = (input as any).scoreEventId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.score.getScoreEvent({ scoreEventId: scoreeventId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${scoreeventId}`);
    }

    return entity as GetScoreEventOutput;
  }
}
