/**
 * DispositionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DispositionRepository Port
 *
 * DDD: Application port for dispositionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDispositionInput, CreateDispositionOutput, ListDispositionsInput, ListDispositionsOutput } from "../dto/disposition.dto";
export interface DispositionRepository {
  listDispositions(input: ListDispositionsInput): Promise<ListDispositionsOutput>;
  createDisposition(input: CreateDispositionInput): Promise<CreateDispositionOutput>;
}

export type { CreateDispositionInput, CreateDispositionOutput, ListDispositionsInput, ListDispositionsOutput } from "../dto/disposition.dto";
