/**
 * PromotionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PromotionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PromotionRepository,
} from "@aegira/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PromotionRepositoryDdb } from "./promotion-repository.ddb.js";

/**
 * PromotionRepositoryAdapter
 *
 * Implements PromotionRepository port for infrastructure layer.
 */
export class PromotionRepositoryAdapter implements PromotionRepository {
  private readonly ddb: PromotionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PromotionRepositoryDdb(this.dynamoClient);
  }

  async listPromotionDecisions(input: Parameters<PromotionRepository['listPromotionDecisions']>[0]): Promise<Awaited<ReturnType<PromotionRepository['listPromotionDecisions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPromotionDecisions(input);
  }

  async proposePromotion(input: Parameters<PromotionRepository['proposePromotion']>[0]): Promise<Awaited<ReturnType<PromotionRepository['proposePromotion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.proposePromotion(input);
  }
}
