/**
 * VModelRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepositoryDdb
 *
 * DDD: Infrastructure adapter for VModel repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { VModelRepository } from "@aegira/services/models";

export class VModelRepositoryDdb implements VModelRepository {
  constructor(private readonly dynamoClient: any) {}

  async listFraudModels(input: Parameters<VModelRepository['listFraudModels']>[0]): Promise<Awaited<ReturnType<VModelRepository['listFraudModels']>>> {
    return handleAegiraSandbox("listFraudModels", input as Record<string, unknown>) as any;
  }

  async getFraudModel(input: Parameters<VModelRepository['getFraudModel']>[0]): Promise<Awaited<ReturnType<VModelRepository['getFraudModel']>>> {
    return handleAegiraSandbox("getFraudModel", input as Record<string, unknown>) as any;
  }
}
