/**
 * CallOutcomeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CallOutcomeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CallOutcomeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CallOutcomeRepository,
} from "@aegira/services/care";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CallOutcomeRepositoryDdb } from "./call-outcome-repository.ddb.js";

/**
 * CallOutcomeRepositoryAdapter
 *
 * Implements CallOutcomeRepository port for infrastructure layer.
 */
export class CallOutcomeRepositoryAdapter implements CallOutcomeRepository {
  private readonly ddb: CallOutcomeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CallOutcomeRepositoryDdb(this.dynamoClient);
  }

  async noteCareCallOutcome(input: Parameters<CallOutcomeRepository['noteCareCallOutcome']>[0]): Promise<Awaited<ReturnType<CallOutcomeRepository['noteCareCallOutcome']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.noteCareCallOutcome(input);
  }
}
