/**
 * StatusRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StatusRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements StatusRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  StatusRepository,
} from "@aegira/services/care";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { StatusRepositoryDdb } from "./status-repository.ddb.js";

/**
 * StatusRepositoryAdapter
 *
 * Implements StatusRepository port for infrastructure layer.
 */
export class StatusRepositoryAdapter implements StatusRepository {
  private readonly ddb: StatusRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new StatusRepositoryDdb(this.dynamoClient);
  }

  async getCareStatus(input: Parameters<StatusRepository['getCareStatus']>[0]): Promise<Awaited<ReturnType<StatusRepository['getCareStatus']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCareStatus(input);
  }
}
