/**
 * Care DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Care Domain Module - Composition root
 *
 * DDD: Composition root for care domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CallOutcomeRepositoryAdapter,
  StatusRepositoryAdapter,
} from "@aegira/adapters/care";
import { getIdGeneratorService } from "@aegira/adapters";
import type { AdapterDynamoDBClient } from "@aegira/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetCareStatus,
  ExecuteNoteCareCallOutcome,
  ExecuteRequestCareCallback,
} from "@aegira/services/care/usecases";
// Ports (interfaces)
import type {
  CallOutcomeRepository,
  StatusRepository,
} from "@aegira/services/care/ports";

export interface CareDomainModule {
  repos: {
    callOutcomes: CallOutcomeRepository;
    statuses: StatusRepository;
  };
  useCases: {
    callOutcomes: {
      get: ExecuteNoteCareCallOutcome;
    };
    statuses: {
      get: ExecuteGetCareStatus;
    };
  };
}

export function buildCareDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CareDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      callOutcomes?: CallOutcomeRepository;
      statuses?: StatusRepository;
    } = {};

    obj.callOutcomes = new CallOutcomeRepositoryAdapter(dynamoClient);
    obj.statuses = new StatusRepositoryAdapter(dynamoClient);
    return {
      callOutcomes: obj.callOutcomes!,
      statuses: obj.statuses!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    callOutcomes: {
      get: new ExecuteNoteCareCallOutcome(executionContext, idGenerator, repos.callOutcomes),
    },
    statuses: {
      get: new ExecuteGetCareStatus(executionContext, idGenerator, repos.statuses),
    },
  };
  return { repos, useCases: useCases as CareDomainModule["useCases"] };
}
