/**
 * AmlHandoffRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmlHandoffRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AmlHandoffRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AmlHandoffRepository,
} from "@aegira/services/handoffs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AmlHandoffRepositoryDdb } from "./aml-handoff-repository.ddb.js";

/**
 * AmlHandoffRepositoryAdapter
 *
 * Implements AmlHandoffRepository port for infrastructure layer.
 */
export class AmlHandoffRepositoryAdapter implements AmlHandoffRepository {
  private readonly ddb: AmlHandoffRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AmlHandoffRepositoryDdb(this.dynamoClient);
  }

  async listAmlHandoffs(input: Parameters<AmlHandoffRepository['listAmlHandoffs']>[0]): Promise<Awaited<ReturnType<AmlHandoffRepository['listAmlHandoffs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAmlHandoffs(input);
  }

  async createAmlHandoff(input: Parameters<AmlHandoffRepository['createAmlHandoff']>[0]): Promise<Awaited<ReturnType<AmlHandoffRepository['createAmlHandoff']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAmlHandoff(input);
  }

  async getAmlHandoff(input: Parameters<AmlHandoffRepository['getAmlHandoff']>[0]): Promise<Awaited<ReturnType<AmlHandoffRepository['getAmlHandoff']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAmlHandoff(input);
  }
}
