/**
 * RejectRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RejectRepositoryDdb
 *
 * DDD: Infrastructure adapter for Reject repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { RejectRepository } from "@aegira/services/handoffs";

export class RejectRepositoryDdb implements RejectRepository {
  constructor(private readonly dynamoClient: any) {}

  async rejectAmlHandoff(input: Parameters<RejectRepository['rejectAmlHandoff']>[0]): Promise<Awaited<ReturnType<RejectRepository['rejectAmlHandoff']>>> {
    return handleAegiraSandbox("rejectAmlHandoff", input as Record<string, unknown>) as any;
  }
}
