/**
 * Repository interface for AmlHandoff
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AmlHandoffEntity
} from "../models/aml-handoff.entity.js";
import type {
  ListAmlHandoffsParams,
  AmlHandoff
} from "../types/index.js";
/**
 * AmlHandoffRepository Interface
 */
export interface AmlHandoffRepository extends CreateReadRepository<AmlHandoffEntity, AmlHandoff, string, ListAmlHandoffsParams> {

}
