/**
 * UndoRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UndoRepositoryDdb
 *
 * DDD: Infrastructure adapter for Undo repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { UndoRepository } from "@aegira/services/dispositions";

export class UndoRepositoryDdb implements UndoRepository {
  constructor(private readonly dynamoClient: any) {}

  async undoDisposition(input: Parameters<UndoRepository['undoDisposition']>[0]): Promise<Awaited<ReturnType<UndoRepository['undoDisposition']>>> {
    return handleAegiraSandbox("undoDisposition", input as Record<string, unknown>) as any;
  }
}
