/**
 * ExecuteListCaseAccessLog - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCaseAccessLog Use Case
 *
 * DDD: Application use case for list CaseAccess.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCaseAccessLogInput, ListCaseAccessLogOutput } from "../dto/case-access.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { CaseAccessRepository } from "../ports";

export class ExecuteListCaseAccessLog {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly caseAccess: CaseAccessRepository
  ) {}

  async execute(input: ListCaseAccessLogInput): Promise<ListCaseAccessLogOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.caseAccess.listCaseAccessLog({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCaseAccessLogOutput;
  }
}
