/**
 * ExecuteGetRetentionPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRetentionPolicy Use Case
 *
 * DDD: Application use case for get Retention.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRetentionPolicyInput, GetRetentionPolicyOutput } from "../dto/retention.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { RetentionRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetRetentionPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly retention: RetentionRepository
  ) {}

  async execute(input: GetRetentionPolicyInput): Promise<GetRetentionPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.retention.getRetentionPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetRetentionPolicyOutput;
  }
}
