/**
 * EntityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EntityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EntityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EntityRepository,
} from "@aegira/services/entities";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EntityRepositoryDdb } from "./entity-repository.ddb.js";

/**
 * EntityRepositoryAdapter
 *
 * Implements EntityRepository port for infrastructure layer.
 */
export class EntityRepositoryAdapter implements EntityRepository {
  private readonly ddb: EntityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EntityRepositoryDdb(this.dynamoClient);
  }

  async listCaseEntities(input: Parameters<EntityRepository['listCaseEntities']>[0]): Promise<Awaited<ReturnType<EntityRepository['listCaseEntities']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCaseEntities(input);
  }
}
