/**
 * HopRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HopRepositoryDdb
 *
 * DDD: Infrastructure adapter for Hop repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { HopRepository } from "@aegira/services/entities";

export class HopRepositoryDdb implements HopRepository {
  constructor(private readonly dynamoClient: any) {}

  async listEntityHops(input: Parameters<HopRepository['listEntityHops']>[0]): Promise<Awaited<ReturnType<HopRepository['listEntityHops']>>> {
    return handleAegiraSandbox("listEntityHops", input as Record<string, unknown>) as any;
  }
}
