/**
 * HopRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HopRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HopRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HopRepository,
} from "@aegira/services/entities";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HopRepositoryDdb } from "./hop-repository.ddb.js";

/**
 * HopRepositoryAdapter
 *
 * Implements HopRepository port for infrastructure layer.
 */
export class HopRepositoryAdapter implements HopRepository {
  private readonly ddb: HopRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HopRepositoryDdb(this.dynamoClient);
  }

  async listEntityHops(input: Parameters<HopRepository['listEntityHops']>[0]): Promise<Awaited<ReturnType<HopRepository['listEntityHops']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEntityHops(input);
  }
}
