/**
 * CaseRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseRepositoryDdb
 *
 * DDD: Infrastructure adapter for Case repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { CaseRepository } from "@aegira/services/cases";

export class CaseRepositoryDdb implements CaseRepository {
  constructor(private readonly dynamoClient: any) {}

  async listFraudCases(input: Parameters<CaseRepository['listFraudCases']>[0]): Promise<Awaited<ReturnType<CaseRepository['listFraudCases']>>> {
    return handleAegiraSandbox("listFraudCases", input as Record<string, unknown>) as any;
  }

  async getFraudCase(input: Parameters<CaseRepository['getFraudCase']>[0]): Promise<Awaited<ReturnType<CaseRepository['getFraudCase']>>> {
    return handleAegiraSandbox("getFraudCase", input as Record<string, unknown>) as any;
  }
}
