/**
 * CaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CaseRepository,
} from "@aegira/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CaseRepositoryDdb } from "./case-repository.ddb.js";

/**
 * CaseRepositoryAdapter
 *
 * Implements CaseRepository port for infrastructure layer.
 */
export class CaseRepositoryAdapter implements CaseRepository {
  private readonly ddb: CaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CaseRepositoryDdb(this.dynamoClient);
  }

  async listFraudCases(input: Parameters<CaseRepository['listFraudCases']>[0]): Promise<Awaited<ReturnType<CaseRepository['listFraudCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFraudCases(input);
  }

  async getFraudCase(input: Parameters<CaseRepository['getFraudCase']>[0]): Promise<Awaited<ReturnType<CaseRepository['getFraudCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFraudCase(input);
  }
}
