/**
 * HeatmapRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HeatmapRepositoryDdb
 *
 * DDD: Infrastructure adapter for Heatmap repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { HeatmapRepository } from "@aegira/services/cases";

export class HeatmapRepositoryDdb implements HeatmapRepository {
  constructor(private readonly dynamoClient: any) {}

  async getQueueHeatmap(input: Parameters<HeatmapRepository['getQueueHeatmap']>[0]): Promise<Awaited<ReturnType<HeatmapRepository['getQueueHeatmap']>>> {
    return handleAegiraSandbox("getQueueHeatmap", input as Record<string, unknown>) as any;
  }
}
