/**
 * HeatmapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HeatmapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HeatmapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HeatmapRepository,
} from "@aegira/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HeatmapRepositoryDdb } from "./heatmap-repository.ddb.js";

/**
 * HeatmapRepositoryAdapter
 *
 * Implements HeatmapRepository port for infrastructure layer.
 */
export class HeatmapRepositoryAdapter implements HeatmapRepository {
  private readonly ddb: HeatmapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HeatmapRepositoryDdb(this.dynamoClient);
  }

  async getQueueHeatmap(input: Parameters<HeatmapRepository['getQueueHeatmap']>[0]): Promise<Awaited<ReturnType<HeatmapRepository['getQueueHeatmap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getQueueHeatmap(input);
  }
}
