/**
 * PriorityPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PriorityPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PriorityPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PriorityPolicyRepository,
} from "@aegira/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PriorityPolicyRepositoryDdb } from "./priority-policy-repository.ddb.js";

/**
 * PriorityPolicyRepositoryAdapter
 *
 * Implements PriorityPolicyRepository port for infrastructure layer.
 */
export class PriorityPolicyRepositoryAdapter implements PriorityPolicyRepository {
  private readonly ddb: PriorityPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PriorityPolicyRepositoryDdb(this.dynamoClient);
  }

  async getPriorityPolicy(input: Parameters<PriorityPolicyRepository['getPriorityPolicy']>[0]): Promise<Awaited<ReturnType<PriorityPolicyRepository['getPriorityPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPriorityPolicy(input);
  }

  async updatePriorityPolicy(input: Parameters<PriorityPolicyRepository['updatePriorityPolicy']>[0]): Promise<Awaited<ReturnType<PriorityPolicyRepository['updatePriorityPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updatePriorityPolicy(input);
  }
}
