/**
 * ReassignRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReassignRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReassignRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReassignRepository,
} from "@aegira/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReassignRepositoryDdb } from "./reassign-repository.ddb.js";

/**
 * ReassignRepositoryAdapter
 *
 * Implements ReassignRepository port for infrastructure layer.
 */
export class ReassignRepositoryAdapter implements ReassignRepository {
  private readonly ddb: ReassignRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReassignRepositoryDdb(this.dynamoClient);
  }

  async reassignFraudCase(input: Parameters<ReassignRepository['reassignFraudCase']>[0]): Promise<Awaited<ReturnType<ReassignRepository['reassignFraudCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.reassignFraudCase(input);
  }
}
