/**
 * ExecuteGetAmlHandoff - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAmlHandoff Use Case
 *
 * DDD: Application use case for get AmlHandoff.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAmlHandoffInput, GetAmlHandoffOutput } from "../dto/aml-handoff.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { AmlHandoffRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAmlHandoff {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly amlHandoff: AmlHandoffRepository
  ) {}

  async execute(input: GetAmlHandoffInput): Promise<GetAmlHandoffOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hndId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).handoffId) {
      throw new ValidationError("handoffId is required");
    }
    const handoffId = (input as any).handoffId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.amlHandoff.getAmlHandoff({ handoffId: handoffId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${handoffId}`);
    }

    return entity as GetAmlHandoffOutput;
  }
}
