/**
 * PromotionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepository Port
 *
 * DDD: Application port for promotionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListPromotionDecisionsInput, ListPromotionDecisionsOutput, ProposePromotionInput, ProposePromotionOutput } from "../dto/promotion.dto";
export interface PromotionRepository {
  listPromotionDecisions(input: ListPromotionDecisionsInput): Promise<ListPromotionDecisionsOutput>;
  proposePromotion(input: ProposePromotionInput): Promise<ProposePromotionOutput>;
}

export type { ListPromotionDecisionsInput, ListPromotionDecisionsOutput, ProposePromotionInput, ProposePromotionOutput } from "../dto/promotion.dto";
