/**
 * RejectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RejectRepository Port
 *
 * DDD: Application port for rejectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RejectPromotionInput, RejectPromotionOutput } from "../dto/reject.dto";
export interface RejectRepository {
  rejectPromotion(input: RejectPromotionInput): Promise<RejectPromotionOutput>;
}

export type { RejectPromotionInput, RejectPromotionOutput } from "../dto/reject.dto";
