/**
 * VModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepository Port
 *
 * DDD: Application port for vmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFraudModelInput, GetFraudModelOutput, ListFraudModelsInput, ListFraudModelsOutput } from "../dto/vmodel.dto";
export interface VModelRepository {
  listFraudModels(input: ListFraudModelsInput): Promise<ListFraudModelsOutput>;
  getFraudModel(input: GetFraudModelInput): Promise<GetFraudModelOutput>;
}

export type { GetFraudModelInput, GetFraudModelOutput, ListFraudModelsInput, ListFraudModelsOutput } from "../dto/vmodel.dto";
