/**
 * GetRetentionPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRetentionPolicy } from "@aegira/api-server/domains/audit/handlers";
import type { AuditDDDDependencies } from "@aegira/api-server/domains/audit";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { AUDIT_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRetentionPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditDDDDependencies>(
      AUDIT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRetentionPolicy, "execute").mockResolvedValue(useCaseResult);

    await getRetentionPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRetentionPolicy.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
