/**
 * PriorityPolicy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/cases.openapi.types.js";
import { schemas } from "../schemas/cases.schemas.js";

/**
 * Entity: PriorityPolicyEntity
 * Description: Represents the PriorityPolicy domain model.
 * Source: schemas.PriorityPolicy
 * Type: Domain Entity (API)
 */
export const PriorityPolicyEntitySchema = schemas.PriorityPolicy;
export type PriorityPolicyEntity = components["schemas"]["PriorityPolicy"];
