/**
 * Routes for AmlHandoff
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAmlHandoff, getAmlHandoff, listAmlHandoffs } from "../handlers/aml-handoff.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function amlHandoffRoutes(fastify: FastifyInstance) {
  // POST /v1/aml-handoffs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/aml-handoffs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHandoffsDependenciesForRequest();
        await createAmlHandoff(request, reply, deps);
      });
    }
  );


  // GET /v1/aml-handoffs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/aml-handoffs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHandoffsDependenciesForRequest();
        await listAmlHandoffs(request, reply, deps);
      });
    }
  );


  // GET /v1/aml-handoffs/{handoffId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/aml-handoffs/:handoffId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { handoffId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHandoffsDependenciesForRequest();
        await getAmlHandoff(request, reply, deps);
      });
    }
  );


}
