/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { acceptRoutes } from "./accept.routes.js";
export { amlHandoffRoutes } from "./aml-handoff.routes.js";
export { rejectRoutes } from "./reject.routes.js";
