/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@aegira/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@aegira/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@aegira/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _audit from "./audit/index.js";
import * as _care from "./care/index.js";
import * as _cases from "./cases/index.js";
import * as _dispositions from "./dispositions/index.js";
import * as _entities from "./entities/index.js";
import * as _experiments from "./experiments/index.js";
import * as _handoffs from "./handoffs/index.js";
import * as _identity from "./identity/index.js";
import * as _metrics from "./metrics/index.js";
import * as _models from "./models/index.js";
import * as _scoring from "./scoring/index.js";

// Export as namespaces
export const audit = _audit;
export const care = _care;
export const cases = _cases;
export const dispositions = _dispositions;
export const entities = _entities;
export const experiments = _experiments;
export const handoffs = _handoffs;
export const identity = _identity;
export const metrics = _metrics;
export const models = _models;
export const scoring = _scoring;
