/**
 * AssurancePackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssurancePackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssurancePackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssurancePackRepository,
} from "@aegira/services/audit";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssurancePackRepositoryDdb } from "./assurance-pack-repository.ddb.js";

/**
 * AssurancePackRepositoryAdapter
 *
 * Implements AssurancePackRepository port for infrastructure layer.
 */
export class AssurancePackRepositoryAdapter implements AssurancePackRepository {
  private readonly ddb: AssurancePackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssurancePackRepositoryDdb(this.dynamoClient);
  }

  async exportAssurancePack(input: Parameters<AssurancePackRepository['exportAssurancePack']>[0]): Promise<Awaited<ReturnType<AssurancePackRepository['exportAssurancePack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.exportAssurancePack(input);
  }
}
