/**
 * CaseAccessRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseAccessRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CaseAccessRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CaseAccessRepository,
} from "@aegira/services/audit";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CaseAccessRepositoryDdb } from "./case-access-repository.ddb.js";

/**
 * CaseAccessRepositoryAdapter
 *
 * Implements CaseAccessRepository port for infrastructure layer.
 */
export class CaseAccessRepositoryAdapter implements CaseAccessRepository {
  private readonly ddb: CaseAccessRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CaseAccessRepositoryDdb(this.dynamoClient);
  }

  async listCaseAccessLog(input: Parameters<CaseAccessRepository['listCaseAccessLog']>[0]): Promise<Awaited<ReturnType<CaseAccessRepository['listCaseAccessLog']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCaseAccessLog(input);
  }
}
