/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./assurance-pack-repository.ddb.js";
export * from "./case-access-repository.ddb.js";
export * from "./promotion-repository.ddb.js";
export * from "./retention-repository.ddb.js";
export * from "./assurance-pack-repository.adapter.js";
export * from "./case-access-repository.adapter.js";
export * from "./promotion-repository.adapter.js";
export * from "./retention-repository.adapter.js";
