/**
 * PromotionRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepositoryDdb
 *
 * DDD: Infrastructure adapter for Promotion repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { PromotionRepository } from "@aegira/services/audit";

export class PromotionRepositoryDdb implements PromotionRepository {
  constructor(private readonly dynamoClient: any) {}

  async listPromotionAudit(input: Parameters<PromotionRepository['listPromotionAudit']>[0]): Promise<Awaited<ReturnType<PromotionRepository['listPromotionAudit']>>> {
    return handleAegiraSandbox("listPromotionAudit", input as Record<string, unknown>) as any;
  }
}
