/**
 * Entity DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Entity DTOs
 *
 * DDD: Application DTOs for Entity use cases.
 */

import type { ListCaseEntitiesParams } from "@aegira/core/entities/types";

export type ListCaseEntitiesInput = ListCaseEntitiesParams;

export type ListCaseEntitiesOutput = {};
