/**
 * ScoreTransaction handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { scoreTransaction } from "@aegira/api-server/domains/scoring/handlers";
import type { ScoringDDDDependencies } from "@aegira/api-server/domains/scoring";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { SCORING_USE_CASES } from "../__factories__/use-cases.js";

describe("ScoreTransaction", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ScoringDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ScoringDDDDependencies>(
      SCORING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeScoreTransaction, "execute").mockResolvedValue(useCaseResult);

    await scoreTransaction(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeScoreTransaction.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
