/**
 * GetAmlHandoff DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAmlHandoffParams } from "@aegira/core/handoffs";

export function createGetAmlHandoffRequest(overrides: Partial<GetAmlHandoffParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
