/**
 * Accept DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Accept DTOs
 *
 * DDD: Application DTOs for Accept use cases.
 */

import type { AcceptAmlHandoffParams } from "@aegira/core/handoffs/types";

export type AcceptAmlHandoffInput = AcceptAmlHandoffParams;

export type AcceptAmlHandoffOutput = {};
