/**
 * RollbackPromotion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { rollbackPromotion } from "@aegira/api-server/domains/models/handlers";
import type { ModelsDDDDependencies } from "@aegira/api-server/domains/models";
import { createCreateRollbackRequest } from "@aegira/factories/models";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { MODELS_USE_CASES } from "../__factories__/use-cases.js";

describe("RollbackPromotion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelsDDDDependencies>(
      MODELS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateRollbackRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRollbackPromotion, "execute").mockResolvedValue(useCaseResult);

    await rollbackPromotion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRollbackPromotion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
