/**
 * Handlers for DispositionMix
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MetricsDomainModule } from "../dependencies/metrics-ddd.dependencies.js";
import type { GetDispositionMixInput } from "@aegira/services/metrics";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/metrics/disposition-mix
 * Operation: getDispositionMix
 */
export async function getDispositionMix(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MetricsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDispositionMixInput = {};
  const result = await deps.useCases.dispositionMixes.get.execute(input);
  return reply.code(200).send(result);
}


