/**
 * Dispositions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dispositions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispositions Domain Module - Composition root
 *
 * DDD: Composition root for dispositions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DispositionRepositoryAdapter,
  UndoRepositoryAdapter,
} from "@aegira/adapters/dispositions";
import { getIdGeneratorService } from "@aegira/adapters";
import type { AdapterDynamoDBClient } from "@aegira/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDisposition,
  ExecuteListDispositions,
  ExecuteUndoDisposition,
} from "@aegira/services/dispositions/usecases";
// Ports (interfaces)
import type {
  DispositionRepository,
  UndoRepository,
} from "@aegira/services/dispositions/ports";

export interface DispositionsDomainModule {
  repos: {
    dispositions: DispositionRepository;
    undos: UndoRepository;
  };
  useCases: {
    dispositions: {
      create: ExecuteCreateDisposition;
      list: ExecuteListDispositions;
    };
    undos: {
      get: ExecuteUndoDisposition;
    };
  };
}

export function buildDispositionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DispositionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dispositions?: DispositionRepository;
      undos?: UndoRepository;
    } = {};

    obj.dispositions = new DispositionRepositoryAdapter(dynamoClient);
    obj.undos = new UndoRepositoryAdapter(dynamoClient);
    return {
      dispositions: obj.dispositions!,
      undos: obj.undos!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dispositions: {
      create: new ExecuteCreateDisposition(executionContext, idGenerator, repos.dispositions),
      list: new ExecuteListDispositions(executionContext, idGenerator, repos.dispositions),
    },
    undos: {
      get: new ExecuteUndoDisposition(executionContext, idGenerator, repos.undos),
    },
  };
  return { repos, useCases: useCases as DispositionsDomainModule["useCases"] };
}
