/**
 * RequestCareCallback handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requestCareCallback } from "@aegira/api-server/domains/care/handlers";
import type { CareDDDDependencies } from "@aegira/api-server/domains/care";
import { createCreateCallbackRequest } from "@aegira/factories/care";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { CARE_USE_CASES } from "../__factories__/use-cases.js";

describe("RequestCareCallback", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CareDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CareDDDDependencies>(
      CARE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateCallbackRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequestCareCallback, "execute").mockResolvedValue(useCaseResult);

    await requestCareCallback(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequestCareCallback.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
