/**
 * AmlHandoffRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmlHandoffRepository Port
 *
 * DDD: Application port for amlhandoffrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAmlHandoffInput, CreateAmlHandoffOutput, GetAmlHandoffInput, GetAmlHandoffOutput, ListAmlHandoffsInput, ListAmlHandoffsOutput } from "../dto/aml-handoff.dto";
export interface AmlHandoffRepository {
  listAmlHandoffs(input: ListAmlHandoffsInput): Promise<ListAmlHandoffsOutput>;
  createAmlHandoff(input: CreateAmlHandoffInput): Promise<CreateAmlHandoffOutput>;
  getAmlHandoff(input: GetAmlHandoffInput): Promise<GetAmlHandoffOutput>;
}

export type { CreateAmlHandoffInput, CreateAmlHandoffOutput, GetAmlHandoffInput, GetAmlHandoffOutput, ListAmlHandoffsInput, ListAmlHandoffsOutput } from "../dto/aml-handoff.dto";
