/**
 * ExecuteListEntityHops - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEntityHops Use Case
 *
 * DDD: Application use case for list Hop.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEntityHopsInput, ListEntityHopsOutput } from "../dto/hop.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegira/services/_shared/index.js";
import type { HopRepository } from "../ports";

export class ExecuteListEntityHops {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hop: HopRepository
  ) {}

  async execute(input: ListEntityHopsInput): Promise<ListEntityHopsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.hop.listEntityHops({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEntityHopsOutput;
  }
}
