/**
 * Handlers for PriorityPolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CasesDomainModule } from "../dependencies/cases-ddd.dependencies.js";
import type { GetPriorityPolicyInput, UpdatePriorityPolicyInput } from "@aegira/services/cases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/queue/priority-policy
 * Operation: getPriorityPolicy
 */
export async function getPriorityPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPriorityPolicyInput = {};
  const result = await deps.useCases.priorityPolicies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/queue/priority-policy
 * Operation: updatePriorityPolicy
 */
export async function updatePriorityPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdatePriorityPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.priorityPolicies.update.execute(input);
  return reply.code(200).send(result);
}


