/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the cases domain.
 * Use these factories in tests to create test data.
 */

export { createCreateClaimRequest } from "./claim/dto/create-claim.dto.factory.js";
export { createPriorityPolicy } from "./priority-policy/entity/priority-policy.entity.factory.js";
