/**
 * DispositionMixRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DispositionMixRepositoryDdb
 *
 * DDD: Infrastructure adapter for DispositionMix repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import { handleAegiraSandbox } from "../_shared/aegira-sandbox.js";
import type { DispositionMixRepository } from "@aegira/services/metrics";

export class DispositionMixRepositoryDdb implements DispositionMixRepository {
  constructor(private readonly dynamoClient: any) {}

  async getDispositionMix(input: Parameters<DispositionMixRepository['getDispositionMix']>[0]): Promise<Awaited<ReturnType<DispositionMixRepository['getDispositionMix']>>> {
    return handleAegiraSandbox("getDispositionMix", input as Record<string, unknown>) as any;
  }
}
