/**
 * LiftRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiftRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LiftRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LiftRepository,
} from "@aegira/services/metrics";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LiftRepositoryDdb } from "./lift-repository.ddb.js";

/**
 * LiftRepositoryAdapter
 *
 * Implements LiftRepository port for infrastructure layer.
 */
export class LiftRepositoryAdapter implements LiftRepository {
  private readonly ddb: LiftRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LiftRepositoryDdb(this.dynamoClient);
  }

  async getWeeklyLift(input: Parameters<LiftRepository['getWeeklyLift']>[0]): Promise<Awaited<ReturnType<LiftRepository['getWeeklyLift']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getWeeklyLift(input);
  }
}
