/**
 * OverviewRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverviewRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OverviewRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OverviewRepository,
} from "@aegira/services/metrics";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OverviewRepositoryDdb } from "./overview-repository.ddb.js";

/**
 * OverviewRepositoryAdapter
 *
 * Implements OverviewRepository port for infrastructure layer.
 */
export class OverviewRepositoryAdapter implements OverviewRepository {
  private readonly ddb: OverviewRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OverviewRepositoryDdb(this.dynamoClient);
  }

  async getOpsMetricsOverview(input: Parameters<OverviewRepository['getOpsMetricsOverview']>[0]): Promise<Awaited<ReturnType<OverviewRepository['getOpsMetricsOverview']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOpsMetricsOverview(input);
  }
}
