/**
 * Handlers for Reject
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { HandoffsDomainModule } from "../dependencies/handoffs-ddd.dependencies.js";
import type { RejectAmlHandoffInput } from "@aegira/services/handoffs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/aml-handoffs/{handoffId}/reject
 * Operation: rejectAmlHandoff
 */
export async function rejectAmlHandoff(
  request: FastifyRequest<{ Params: { handoffId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: HandoffsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RejectAmlHandoffInput = {
    handoffId: request.params.handoffId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rejects.create.execute(input);
  return reply.code(200).send(result);
}


