/**
 * GetAmlHandoff handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAmlHandoff } from "@aegira/api-server/domains/handoffs/handlers";
import type { HandoffsDDDDependencies } from "@aegira/api-server/domains/handoffs";
import { createAmlHandoff as createAmlHandoffEntity } from "@aegira/factories/handoffs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { HANDOFFS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAmlHandoff", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: HandoffsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<HandoffsDDDDependencies>(
      HANDOFFS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAmlHandoffEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAmlHandoff, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { handoffId: entity.id };

    await getAmlHandoff(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAmlHandoff.execute).toHaveBeenCalledWith(expect.objectContaining({ handoffId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { handoffId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAmlHandoff, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAmlHandoff(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
