/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-aml-handoff.handler.test.js";
export * from "./get-aml-handoff.handler.test.js";
export * from "./list-aml-handoffs.handler.test.js";
