/**
 * ListAmlHandoffs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: handoffs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAmlHandoffs } from "@aegira/api-server/domains/handoffs/handlers";
import type { HandoffsDDDDependencies } from "@aegira/api-server/domains/handoffs";
import { createAmlHandoff as createAmlHandoffEntity } from "@aegira/factories/handoffs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegira/tests/shared";
import { HANDOFFS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAmlHandoffs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: HandoffsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<HandoffsDDDDependencies>(
      HANDOFFS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAmlHandoffEntity({ orgId }),
      createAmlHandoffEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAmlHandoffs, "execute").mockResolvedValue(useCaseResult);

    await listAmlHandoffs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAmlHandoffs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
