/**
 * Routes for Reassign
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { reassignFraudCase } from "../handlers/reassign.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function reassignRoutes(fastify: FastifyInstance) {
  // POST /v1/cases/{caseId}/reassign (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/cases/:caseId/reassign",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await reassignFraudCase(request, reply, deps);
      });
    }
  );


}
