/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { statusRoutes } from "./status.routes.js";
export { callOutcomeRoutes } from "./call-outcome.routes.js";
export { callbackRoutes } from "./callback.routes.js";
