/**
 * Handlers for Status
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: care
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CareDomainModule } from "../dependencies/care-ddd.dependencies.js";
import type { GetCareStatusInput } from "@aegira/services/care";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/care/status
 * Operation: getCareStatus
 */
export async function getCareStatus(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { paymentRef?: string | string[], maskedPan?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CareDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCareStatusInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.statuses.get.execute(input);
  return reply.code(200).send(result);
}


