/**
 * Lift DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Lift DTOs
 *
 * DDD: Application DTOs for Lift use cases.
 */

export type GetWeeklyLiftInput = {};

export type GetWeeklyLiftOutput = {};
