/**
 * Handlers for Rollback
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { RollbackPromotionInput } from "@aegira/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/promotions/{promotionId}/rollback
 * Operation: rollbackPromotion
 */
export async function rollbackPromotion(
  request: FastifyRequest<{ Params: { promotionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RollbackPromotionInput = {
    promotionId: request.params.promotionId,
  };
  const result = await deps.useCases.rollbacks.get.execute(input);
  return reply.code(200).send(result);
}


